contentColumnType: text
fieldGroup: 0815347a-8e73-45fd-93c9-2244ac562559 # Contact Info
handle: address
instructions: ''
name: Address
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
