fieldLayouts:
  da21546b-da53-49c7-8821-2685c67df6b4:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: companyLogos
hasUrls: true
name: 'Company Logos'
settings:
  path: '@assetBasePath/logos'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\volumes\Local
url: '@assetBaseUrl/logos'
